# Generated by Django 4.1.7 on 2023-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('userprofile_id', models.IntegerField(default=0)),
                ('product_discription', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
