# Generated by Django 4.1.7 on 2023-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ImageField(default=0, upload_to='')),
                ('pid', models.ImageField(default=0, upload_to='')),
            ],
        ),
    ]
