# Generated by Django 4.1.7 on 2023-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_cart_pid_alter_cart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default=None, max_length=40)),
                ('password', models.CharField(default=None, max_length=300)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.ImageField(default=0, max_length=11, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='SignUpUser',
        ),
    ]
